<#
  OpsPoint for Windows: the maintenance tool (Start menu: "OpsPoint Setup"), and the
  questions OpsPoint Setup asks after it has copied the files.

    opspoint.ps1                        the menu (arrow keys or number keys)
    opspoint.ps1 -Configure             the install questions, the service, the setup link
    opspoint.ps1 doctor | export | import FILE | drill FOLDER | settings | migrate | setup-code
                                        the command line
    -Config answers.env -Yes            unattended (no questions)    -NoColor   plain text
    -DryRun                             say what would happen; change nothing

  Answers (KEY=value lines, all optional): TZ, PORT, OPSPOINT_DATA, OPSPOINT_DB_DRIVER
  (sqlite or pg), DATABASE_URL, ADDRESS.
  Windows PowerShell 5.1 or later; run as administrator for -Configure, upgrades and uninstall.
#>
[CmdletBinding()]
param(
  [Parameter(Position = 0)] [string] $Command = '',
  [Parameter(Position = 1, ValueFromRemainingArguments = $true)] [string[]] $Rest = @(),
  [switch] $Configure, [switch] $RemoveService,
  [string] $Config = '', [switch] $Yes, [switch] $NoColor, [switch] $DryRun,
  [string] $InstallDir = ''
)
$ErrorActionPreference = 'Stop'
Set-StrictMode -Version 2

# ── brand (generated by scripts/gen-brand.cjs from packaging/brand.json) ──
$BrandProduct = 'OpsPoint'
$BrandTitle   = 'OpsPoint Setup'
$BrandTagline = 'Residential operations'
$BrandDoor    = '◖▌░░◗'
$Palette = @{
  navy   = @{ Hex = '#1E3A70'; A256 = 24; A16 = 34 }
  gold   = @{ Hex = '#F5B82E'; A256 = 214; A16 = 33 }
  warm   = @{ Hex = '#FFE8A3'; A256 = 229; A16 = 97 }
  silver = @{ Hex = '#C5CBD3'; A256 = 251; A16 = 37 }
  pass   = @{ Hex = '#16A34A'; A256 = 34; A16 = 32 }
  fail   = @{ Hex = '#DC2626'; A256 = 160; A16 = 31 }
}
$MenuQuestion = 'What would you like to do?'
$MenuItems = @(
  @{ Key = '1'; Id = 'install'; Label = 'Install OpsPoint' }
  @{ Key = '2'; Id = 'upgrade'; Label = 'Upgrade or repair' }
  @{ Key = '3'; Id = 'doctor'; Label = 'Health check' }
  @{ Key = '4'; Id = 'backup'; Label = 'Back up or restore' }
  @{ Key = '5'; Id = 'export'; Label = 'Export or import' }
  @{ Key = '6'; Id = 'uninstall'; Label = 'Uninstall' }
  @{ Key = 'q'; Id = 'quit'; Label = 'Quit' }
)
$MenuHints = '↑↓ move · Enter select · Q quit'
$Words = @{
  checking = 'Checking this machine'
  installing = 'Installing'
  done = 'OpsPoint is installed'
  openSetup = 'Open this link to finish setup'
  setupCode = 'Setup code'
  codeNote = 'works once, for 24 hours'
  phoneNote = 'Scan it with a phone to finish setup there'
}
# ── end brand ──

$Releases  = 'https://github.com/harrisb415/opspoint-releases/releases'
$TaskName  = 'OpsPoint'
$CliCommands = @('settings', 'doctor', 'migrate', 'keys', 'setup-code', 'export', 'import', 'drill')
if (-not $InstallDir) { $InstallDir = $PSScriptRoot }
$App      = Join-Path $InstallDir 'app'
$NodeExe  = Join-Path $InstallDir 'node\node.exe'
$Settings = Join-Path $App 'opspoint.config.json'
$NetworkService = '*S-1-5-20'

# ── Colour: VT sequences on Windows 10+ consoles; none for NO_COLOR, -NoColor or a pipe ──
$UseColor = (-not $NoColor) -and (-not $env:NO_COLOR) -and (-not [Console]::IsOutputRedirected)
if ($UseColor) {
  try {
    Add-Type -Namespace OpsPoint -Name Vt -MemberDefinition @'
[DllImport("kernel32.dll")] public static extern IntPtr GetStdHandle(int h);
[DllImport("kernel32.dll")] public static extern bool GetConsoleMode(IntPtr h, out uint m);
[DllImport("kernel32.dll")] public static extern bool SetConsoleMode(IntPtr h, uint m);
'@ -ErrorAction Stop
    $h = [OpsPoint.Vt]::GetStdHandle(-11); $m = 0
    if ([OpsPoint.Vt]::GetConsoleMode($h, [ref]$m)) { [void][OpsPoint.Vt]::SetConsoleMode($h, $m -bor 0x4) } else { $UseColor = $false }
  } catch { $UseColor = $false }
}
try { [Console]::OutputEncoding = [Text.Encoding]::UTF8 } catch { }
$E = [char]27
function Fg([string]$name) {
  if (-not $UseColor) { return '' }
  $h = $Palette[$name].Hex
  return "$E[38;2;$([Convert]::ToInt32($h.Substring(1,2),16));$([Convert]::ToInt32($h.Substring(3,2),16));$([Convert]::ToInt32($h.Substring(5,2),16))m"
}
function Bg([string]$name) {
  if (-not $UseColor) { return '' }
  $h = $Palette[$name].Hex
  return "$E[48;2;$([Convert]::ToInt32($h.Substring(1,2),16));$([Convert]::ToInt32($h.Substring(3,2),16));$([Convert]::ToInt32($h.Substring(5,2),16))m"
}
$Off = ''; $Bold = ''; $Dim = ''
if ($UseColor) { $Off = "$E[0m"; $Bold = "$E[1m"; $Dim = "$E[2m" }
$Gold = Fg 'gold'; $Silver = Fg 'silver'; $Warm = Fg 'warm'; $Pass = Fg 'pass'; $Fail = Fg 'fail'; $NavyBg = Bg 'navy'
$Interactive = (-not $Yes) -and (-not [Console]::IsInputRedirected) -and (-not [Console]::IsOutputRedirected)

function Say([string]$t) { Write-Host $t }
function Head1([string]$t) { Write-Host ''; Write-Host "   $Gold$Bold$t$Off" }
function Ok([string]$t) { Write-Host "   $Pass✔$Off $t" }
function Bad([string]$t) { Write-Host "   $Fail✖$Off $t" }
function Note([string]$t) { Write-Host "   $Gold!$Off $t" }
function Die([string]$t) { Write-Host ''; Write-Host "   $Fail✖ $t$Off"; Write-Host ''; exit 1 }

function Banner([string]$ver = '') {
  $w = 48
  $line = '─' * $w
  $l1 = "   $BrandDoor   $BrandTitle"; if ($ver) { $l1 += " · v$ver" }
  $l2 = "           $BrandTagline"
  Write-Host ''
  Write-Host "  $NavyBg$Silver╭$line╮$Off"
  Write-Host "  $NavyBg$Silver│$Gold$Bold$($l1.PadRight($w))$Off$NavyBg$Silver│$Off"
  Write-Host "  $NavyBg$Silver│$Silver$($l2.PadRight($w))$NavyBg$Silver│$Off"
  Write-Host "  $NavyBg$Silver╰$line╯$Off"
  Write-Host ''
}

function Progress([int]$pct, [string]$what) {
  $fill = [int][Math]::Floor($pct * 20 / 100)
  $bar = ('█' * $fill) + ('░' * (20 - $fill))
  if ($Interactive) { Write-Host -NoNewline ("`r   {0} {1}{2}{3} {4,3}%  {5}" -f $Words.installing, $Gold, $bar, $Off, $pct, $what.PadRight(40)) }
  else { Write-Host ("   {0} {1,3}%  {2}" -f $Words.installing, $pct, $what) }
}
function ProgressEnd { if ($Interactive) { Write-Host '' } }

# Arrow keys and number keys; a numbered prompt when there is no console to draw on.
function Menu([string]$question, [object[]]$items, [string]$defaultId = '') {
  if (-not $Interactive) {
    Write-Host "   $question"
    foreach ($i in $items) { Write-Host "     $($i.Key)) $($i.Label)" }
    while ($true) {
      $a = Read-Host '   Choose'
      foreach ($i in $items) { if ($i.Key -eq $a.ToLower()) { return $i.Id } }
    }
  }
  # Where the highlight starts: Enter alone must never start something heavy.
  $sel = 0; $n = $items.Count
  for ($k = 0; $k -lt $n; $k++) { if ($items[$k].Id -eq $defaultId) { $sel = $k } }
  Write-Host "   $question"; Write-Host ''
  $top = [Console]::CursorTop
  while ($true) {
    [Console]::SetCursorPosition(0, $top)
    for ($k = 0; $k -lt $n; $k++) {
      if ($k -eq $sel) { Write-Host ("   $Gold$Bold▸ " + $items[$k].Label + "$Off").PadRight(60) }
      else { Write-Host ("     $Silver" + $items[$k].Label + "$Off").PadRight(60) }
    }
    Write-Host ''; Write-Host "   $Dim$MenuHints$Off"
    $key = [Console]::ReadKey($true)
    switch ($key.Key) {
      'UpArrow'   { $sel = ($sel + $n - 1) % $n; continue }
      'DownArrow' { $sel = ($sel + 1) % $n; continue }
      'Enter'     { Write-Host ''; return $items[$sel].Id }
      'Escape'    { Write-Host ''; return 'quit' }
    }
    foreach ($i in $items) { if ($i.Key -eq ([string]$key.KeyChar).ToLower()) { Write-Host ''; return $i.Id } }
  }
}

function Ask([string]$name, [string]$question, [string]$default) {
  $v = Get-Variable -Name "A_$name" -ValueOnly -ErrorAction SilentlyContinue
  if ($v) { return $v }
  if (-not $Interactive) { return $default }
  $a = Read-Host "   $question [$default]"
  if ([string]::IsNullOrWhiteSpace($a)) { return $default }
  return $a.Trim()
}
function YesNo([string]$question, [bool]$default = $true) {
  if (-not $Interactive) { return $default }
  $hint = '[y/N]'; if ($default) { $hint = '[Y/n]' }
  $a = Read-Host "   $question $hint"
  if ([string]::IsNullOrWhiteSpace($a)) { return $default }
  return $a.Trim().ToLower().StartsWith('y')
}

function Run([scriptblock]$block, [string]$what) {
  if ($DryRun) { Say "   would $what"; return }
  & $block
}

# ── Answers: KEY=value lines, read as data ─────────────────────────────────
$AllowedAnswers = @('TZ', 'PORT', 'OPSPOINT_DATA', 'OPSPOINT_DB_DRIVER', 'DATABASE_URL', 'PGSSLMODE', 'ADDRESS')
if ($Config) {
  if (-not (Test-Path -LiteralPath $Config)) { Die "Can't read the answers file $Config." }
  foreach ($raw in Get-Content -LiteralPath $Config -Encoding UTF8) {
    $line = $raw.Trim()
    if (-not $line -or $line.StartsWith('#')) { continue }
    if ($line -notmatch '^([A-Z_][A-Z0-9_]*)=(.*)$') { Die "Not a KEY=value line in ${Config}: $line" }
    $k = $Matches[1]; $v = $Matches[2].Trim().Trim('"').Trim("'")
    if ($AllowedAnswers -notcontains $k) { Die "${Config}: $k isn't an answer this installer takes." }
    Set-Variable -Name "A_$k" -Value $v -Scope Script
  }
}

function Installed { return (Test-Path -LiteralPath (Join-Path $App 'package.json')) }
function InstalledVersion {
  try { return (Get-Content -LiteralPath (Join-Path $App 'package.json') -Raw | ConvertFrom-Json).version } catch { return '' }
}
function ReadSettings {
  if (Test-Path -LiteralPath $Settings) { return (Get-Content -LiteralPath $Settings -Raw | ConvertFrom-Json) }
  return $null
}

# The OpsPoint command line, with this install's settings.
function Cli([string[]]$cliArgs) {
  if (-not (Test-Path -LiteralPath $NodeExe)) { Die "Node.js isn't in $InstallDir\node: run OpsPoint Setup again." }
  Push-Location $App
  try { & $NodeExe (Join-Path $App 'server\cli\opspoint.js') @cliArgs; return $LASTEXITCODE } finally { Pop-Location }
}

function WaitHealthy([int]$port) {
  if ($DryRun) { Say "   would wait for http://127.0.0.1:$port/healthz"; return $true }
  for ($i = 0; $i -lt 45; $i++) {
    try {
      $r = Invoke-WebRequest -UseBasicParsing -TimeoutSec 2 -Uri "http://127.0.0.1:$port/healthz"
      if ($r.StatusCode -eq 200) { return $true }
    } catch { }
    Start-Sleep -Seconds 2
  }
  return $false
}

function FirstAddress {
  try {
    $a = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction Stop |
      Where-Object { $_.IPAddress -notlike '127.*' -and $_.IPAddress -notlike '169.254.*' -and $_.PrefixOrigin -ne 'WellKnown' } |
      Select-Object -First 1
    if ($a) { return $a.IPAddress }
  } catch { }
  return $env:COMPUTERNAME
}

# ── The service: a scheduled task at boot, as NETWORK SERVICE ──────────────
function RegisterService {
  $action = New-ScheduledTaskAction -Execute $NodeExe -Argument "`"$App\bootstrap.js`"" -WorkingDirectory $App
  $trigger = New-ScheduledTaskTrigger -AtStartup
  $principal = New-ScheduledTaskPrincipal -UserId 'NT AUTHORITY\NETWORKSERVICE' -LogonType ServiceAccount
  $taskSettings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable `
    -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1) -ExecutionTimeLimit ([TimeSpan]::Zero)
  Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Principal $principal -Settings $taskSettings -Force | Out-Null
}
function StartService { Run { Start-ScheduledTask -TaskName $TaskName } "start the $TaskName task" }
function StopService {
  Run {
    try { Stop-ScheduledTask -TaskName $TaskName -ErrorAction Stop } catch { }
    # The task's node process outlives Stop-ScheduledTask: end the one running from this folder.
    Get-CimInstance Win32_Process -Filter "Name='node.exe'" | Where-Object { $_.ExecutablePath -eq $NodeExe } |
      ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }
  } "stop the $TaskName task"
}

# ── Install: the questions, the settings file, the service, the setup link ──
function Do-Configure {
  $t0 = Get-Date
  Head1 $Words.checking
  if (-not $DryRun) {
    $admin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
    if (-not $admin) { Die 'Run OpsPoint Setup as an administrator.' }
  }
  $os = (Get-CimInstance Win32_OperatingSystem -ErrorAction SilentlyContinue)
  if ($os) { Ok "$($os.Caption) ($($os.Version))" }
  if (Test-Path -LiteralPath $NodeExe) { Ok "Node $(& $NodeExe -p 'process.versions.node') (bundled)" } elseif (-not $DryRun) { Die "Node.js is missing from $InstallDir\node: run OpsPoint Setup again." }
  $zone = 'UTC'
  if (Test-Path -LiteralPath $NodeExe) { $zone = (& $NodeExe -p 'Intl.DateTimeFormat().resolvedOptions().timeZone') }
  $tz = Ask 'TZ' "The facility's time zone" $zone
  $port = Ask 'PORT' 'Port OpsPoint answers on' '3000'
  if ($port -notmatch '^\d+$' -or [int]$port -lt 1 -or [int]$port -gt 65535) { Die 'PORT must be a number from 1 to 65535.' }
  $data = Ask 'OPSPOINT_DATA' 'Folder for the database, photos and backups' (Join-Path $env:ProgramData 'OpsPoint')
  $driver = Get-Variable -Name 'A_OPSPOINT_DB_DRIVER' -ValueOnly -ErrorAction SilentlyContinue
  if (-not $driver) {
    if ($Interactive) { $driver = Menu 'Where does the database live?' @(@{ Key = '1'; Id = 'sqlite'; Label = 'SQLite on this PC (encrypted; simplest)' }, @{ Key = '2'; Id = 'pg'; Label = 'Postgres on another server' }) }
    else { $driver = 'sqlite' }
  }
  if ($driver -ne 'sqlite' -and $driver -ne 'pg') { Die 'OPSPOINT_DB_DRIVER must be sqlite or pg.' }
  $url = ''; $ssl = ''
  if ($driver -eq 'pg') {
    $url = Ask 'DATABASE_URL' 'Postgres connection string (postgresql://user:password@host:5432/database)' ''
    if ($url -notmatch '^postgres(ql)?://') { Die 'DATABASE_URL must be a postgresql:// connection string.' }
    # TLS to the database: verified by default; a database on this PC needs none.
    $dbhost = $url -replace '^[a-z]+://([^@]*@)?(\[[^\]]*\]|[^/:?]*).*$', '$2'
    $sslDefault = 'verify-full'; if (@('localhost', '127.0.0.1', '[::1]') -contains $dbhost) { $sslDefault = 'disable' }
    $ssl = Ask 'PGSSLMODE' 'TLS to the database (verify-full, verify-ca, require or disable)' $sslDefault
    if (@('disable', 'require', 'verify-ca', 'verify-full') -notcontains $ssl) { Die 'PGSSLMODE must be verify-full, verify-ca, require or disable.' }
  }
  $busy = $null
  try { $busy = Get-NetTCPConnection -LocalPort ([int]$port) -State Listen -ErrorAction Stop } catch { }
  if ($busy -and -not (Installed)) { Bad "Port $port is in use"; if (-not $DryRun) { Die "Something else answers on port ${port}: choose another." } } else { Ok "Port $port is free" }
  $drive = (Split-Path -Qualifier $data)
  $free = (Get-PSDrive -Name $drive.TrimEnd(':') -ErrorAction SilentlyContinue)
  if ($free) { $gb = [int]($free.Free / 1GB); if ($gb -ge 2) { Ok "$gb GB free disk space" } else { Bad "Only $gb GB free on $drive"; if (-not $DryRun) { Die 'OpsPoint needs at least 2 GB free.' } } }
  Ok "Time zone $tz"
  if ($driver -eq 'pg') { Ok ("Database: Postgres at " + ($url -replace '^[a-z]+://([^@]*@)?([^/?]*).*$', '$2')) } else { Ok "Database: SQLite in $data" }
  Write-Host ''

  Progress 20 'Writing the settings…'
  $s = [ordered]@{ OPSPOINT_PROFILE = 'windows-local'; TZ = $tz; PORT = [int]$port; OPSPOINT_DATA = $data; OPSPOINT_DB_DRIVER = $driver }
  if ($driver -eq 'pg') { $s.DATABASE_URL = $url; $s.PGSSLMODE = $ssl }
  $json = $s | ConvertTo-Json
  if ($DryRun) {
    ProgressEnd; Say "   would write $Settings"
    ($json -replace '("DATABASE_URL":\s*"[a-z]+://[^:/@]*:)[^@]*@', '$1•••@') -split "`n" | ForEach-Object { Say "     | $($_.TrimEnd())" }
  } else {
    New-Item -ItemType Directory -Force -Path $data | Out-Null
    [IO.File]::WriteAllText($Settings, $json + "`r`n", (New-Object Text.UTF8Encoding($false)))
    # The service account reads the settings, writes the data folder, and updates the app in place.
    & icacls $data /grant "${NetworkService}:(OI)(CI)M" /T /Q | Out-Null
    & icacls $App /grant "${NetworkService}:(OI)(CI)M" /T /Q | Out-Null
    & icacls $Settings /inheritance:r /grant:r "*S-1-5-32-544:F" "*S-1-5-18:F" "${NetworkService}:R" /Q | Out-Null
  }
  Progress 60 'Registering the service…'
  Run { RegisterService } "register the scheduled task $TaskName (at startup, as NETWORK SERVICE, restarted on failure)"
  Progress 80 'Starting OpsPoint…'
  StartService
  if (-not (WaitHealthy ([int]$port))) { ProgressEnd; Die "OpsPoint didn't start. See $data\logs, or run: opspoint doctor" }
  Progress 100 'Started.'
  ProgressEnd
  Finish-Card $t0 ([int]$port) $data
}

function Finish-Card([datetime]$t0, [int]$port, [string]$data) {
  Head1 'Health check'
  if ($DryRun) { Say '   would run: opspoint doctor' } else { [void](Cli @('doctor')) }
  $addr = Get-Variable -Name 'A_ADDRESS' -ValueOnly -ErrorAction SilentlyContinue
  if (-not $addr) { $addr = FirstAddress }
  $scheme = 'http'; if (Test-Path -LiteralPath (Join-Path $data 'cert.pem')) { $scheme = 'https' }
  $link = "${scheme}://${addr}:$port/setup"
  $code = ''
  if (-not $DryRun) {
    $out = (Cli @('setup-code') 6>&1 2>$null | Out-String)
    if ($out -match 'Setup code: ([A-Z0-9-]+)') { $code = $Matches[1] }
  }
  Write-Host ''
  Write-Host ("   $Gold$Bold{0}$Off  ({1}s)" -f $Words.done, [int]((Get-Date) - $t0).TotalSeconds)
  Write-Host ''
  Write-Host "   $($Words.openSetup):"
  Write-Host "   $Warm$Bold$link$Off"
  if ($code) { Write-Host "   $($Words.setupCode): $Warm$Bold$code$Off ($($Words.codeNote))" }
  elseif (-not $DryRun) { Write-Host '   Setup is already finished here: sign in as usual.' }
  if ($Interactive -and -not $DryRun) { Start-Process "http://localhost:$port/setup" }
  Write-Host ''
  Write-Host "   ${Dim}Later: Start menu > OpsPoint Setup (upgrade, health check, backup, export)$Off"
  Write-Host ''
}

# ── Backup, export, import, upgrade, uninstall ─────────────────────────────
function Do-Backup {
  if (-not (Installed)) { Die "OpsPoint isn't installed in $InstallDir." }
  $data = (ReadSettings).OPSPOINT_DATA
  switch (Menu 'Back up or restore' @(@{ Key = '1'; Id = 'export'; Label = 'Export now (one encrypted file with everything)' }, @{ Key = '2'; Id = 'drill'; Label = 'Restore drill: the newest export into a scratch install' }, @{ Key = '3'; Id = 'list'; Label = 'Open the backups folder' }, @{ Key = 'b'; Id = 'back'; Label = 'Back' })) {
    'export' { [void](Cli @('export', '--out', (Join-Path $data 'exports'))) }
    'drill'  { [void](Cli @('drill', (Join-Path $data 'exports'))) }
    'list'   { Start-Process explorer.exe (Join-Path $data 'backups') }
  }
}
function Do-Export {
  if (-not (Installed)) { Die "OpsPoint isn't installed in $InstallDir." }
  $st = ReadSettings
  switch (Menu 'Export or import' @(@{ Key = '1'; Id = 'export'; Label = 'Export to a file' }, @{ Key = '2'; Id = 'import'; Label = 'Import an export (into this new, empty install)' }, @{ Key = 'b'; Id = 'back'; Label = 'Back' })) {
    'export' { $to = Ask 'EXPORT_TO' 'Folder or file for the export' (Join-Path $st.OPSPOINT_DATA 'exports'); [void](Cli @('export', '--out', $to)) }
    'import' {
      $file = Ask 'IMPORT_FILE' 'The export file to import' ''
      if (-not (Test-Path -LiteralPath $file)) { Die "There is no file at $file." }
      StopService
      $rc = Cli @('import', $file)
      StartService
      if ($rc -eq 0) { Finish-Card (Get-Date) ([int]$st.PORT) $st.OPSPOINT_DATA }
    }
  }
}
function Do-Upgrade {
  if (-not (Installed)) { Die "OpsPoint isn't installed in $InstallDir." }
  Head1 "Upgrade or repair (installed: v$(InstalledVersion))"
  Say '   OpsPoint updates itself: Admin > System > Software updates checks, downloads, verifies'
  Say '   the release signature and installs, keeping the previous version to roll back to.'
  Say "   To repair, or to move to a new major version, run the newest OpsPoint Setup from:"
  Say "   $Warm$Releases/latest$Off"
  if (YesNo 'Open that page now?' $true) { Start-Process "$Releases/latest" }
}
function Do-Uninstall {
  $un = Get-ChildItem -LiteralPath $InstallDir -Filter 'unins*.exe' -ErrorAction SilentlyContinue | Select-Object -First 1
  if (-not $un) { Die 'No uninstaller here: use Settings > Apps > OpsPoint.' }
  Say '   The uninstaller removes the program. The data folder (database, photos, backups) stays.'
  if (YesNo 'Run it now?' $false) { Start-Process $un.FullName; exit 0 }
}
function Remove-Service {
  StopService
  Run { try { Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction Stop } catch { } } "remove the scheduled task $TaskName"
}

# ── Main ────────────────────────────────────────────────────────────────────
if ($RemoveService) { Remove-Service; exit 0 }
if ($Configure) {
  Banner; Do-Configure
  # Setup's console closes with this script: keep the link and the code on screen until read.
  if ($Interactive) { [void](Read-Host "   ${Dim}Press Enter to close this window$Off") }
  exit 0
}
if ($Command) {
  if ($CliCommands -notcontains $Command) { Die "Unknown command $Command (see the top of this script)." }
  if (-not (Installed)) { Die "OpsPoint isn't installed in $InstallDir." }
  exit (Cli (@($Command) + $Rest))
}
while ($true) {
  $ver = ''; if (Installed) { $ver = InstalledVersion }
  Banner $ver
  $start = 'install'; if (Installed) { $start = 'doctor' }
  switch (Menu $MenuQuestion $MenuItems $start) {
    'install'   { if (Installed) { Note "OpsPoint $ver is installed. Choose Upgrade or repair." } else { Note 'Run OpsPoint Setup (the installer) to install OpsPoint.' } }
    'upgrade'   { Do-Upgrade }
    'doctor'    { if (-not (Installed)) { Die "OpsPoint isn't installed in $InstallDir." }; [void](Cli @('doctor')) }
    'backup'    { Do-Backup }
    'export'    { Do-Export }
    'uninstall' { Do-Uninstall }
    'quit'      { exit 0 }
  }
  if (-not $Interactive) { exit 0 }
  [void](Read-Host "   ${Dim}Press Enter for the menu$Off")
}
