-- ============================================================================
-- 002_central_schema.sql — OpsPoint Central (HQ) database, PostgreSQL 18
--
-- Hand-converted from central/db.js. Same conventions as 001.
--
-- SEPARATE DATABASE. Central is its own store with its own lifecycle — it is
-- not a schema inside the facility database. Whether it lives in a second
-- PostgreSQL database on the same cluster or the same database under a
-- `central` schema is a deployment decision; this file assumes a separate
-- database named `opscentral`, matching how central/db.js opens its own file
-- today. Nothing here cross-references the facility tables.
--
-- Note on identity: only central_users and audit are identity columns.
-- facilities.id and managed_users.id are TEXT UUIDs generated by the
-- application at enrollment, so the explicit-id inserts at central/db.js:447
-- and :608 are normal and need no OVERRIDING clause.
-- ============================================================================

BEGIN;

-- ── settings ────────────────────────────────────────────────────────────────
-- Same mixed raw-string/JSON storage as the facility settings table. Stays text.
CREATE TABLE settings (
  key   text PRIMARY KEY,
  value text
);

-- ── central_users ───────────────────────────────────────────────────────────
-- Org-level administrators. Never sync down to a facility.
CREATE TABLE central_users (
  id             integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  username       text        NOT NULL UNIQUE,
  display_name   text        NOT NULL DEFAULT '',
  role           text        NOT NULL DEFAULT 'admin',
  hash           text,
  salt           text,
  must_change_pw smallint    NOT NULL DEFAULT 0 CHECK (must_change_pw IN (0,1)),
  created_at     timestamptz NOT NULL DEFAULT now()
);

-- ── facilities ──────────────────────────────────────────────────────────────
-- id is a UUID minted at enrollment and handed to the facility node.
-- Only the SHA-256 of the API key is stored; the key itself is shown once.
CREATE TABLE facilities (
  id             text        PRIMARY KEY,
  name           text        NOT NULL,
  api_key_hash   text        NOT NULL UNIQUE,
  api_key_prefix text        NOT NULL DEFAULT '',
  status         text        NOT NULL DEFAULT 'active'
                 CHECK (status IN ('active','disabled')),
  app_version    text        NOT NULL DEFAULT '',
  last_seen_at   timestamptz,
  last_seen_ip   text        NOT NULL DEFAULT '',
  created_at     timestamptz NOT NULL DEFAULT now()
);

-- ── sync_state ──────────────────────────────────────────────────────────────
-- applied_through is a monotonic cursor into the facility's sync_outbox ids.
CREATE TABLE sync_state (
  facility_id     text PRIMARY KEY REFERENCES facilities (id) ON DELETE CASCADE,
  applied_through bigint      NOT NULL DEFAULT 0,
  updated_at      timestamptz
);

-- ── audit ───────────────────────────────────────────────────────────────────
CREATE TABLE audit (
  id     integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ts     timestamptz NOT NULL DEFAULT now(),
  actor  text        NOT NULL DEFAULT '',
  action text        NOT NULL,
  target text        NOT NULL DEFAULT '',
  detail text        NOT NULL DEFAULT '',
  ip     text        NOT NULL DEFAULT ''
);
CREATE INDEX idx_central_audit_ts ON audit (ts DESC);

-- ── facility_data ───────────────────────────────────────────────────────────
-- Generic synced-row store, keyed by (facility_id, table_name, source_id).
--
-- `data` is the one column where jsonb is genuinely tempting: it is always JSON,
-- never a raw string, and central/db.js already reads it with json_extract for
-- Phase 2 reporting. json_extract is SQLite-only and has no PostgreSQL
-- equivalent, so those call sites must be rewritten regardless — to `data->>'x'`
-- if this becomes jsonb, or to application-side JSON.parse if it stays text.
--
-- Kept as text here for consistency with the facility migration. If you would
-- rather take jsonb now, this is the column to take it on, and the rewrite cost
-- is already paid. Flagging rather than deciding.
CREATE TABLE facility_data (
  facility_id text        NOT NULL REFERENCES facilities (id) ON DELETE CASCADE,
  table_name  text        NOT NULL,
  source_id   bigint      NOT NULL,
  data        text,
  updated_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (facility_id, table_name, source_id)
);
CREATE INDEX idx_fdata_fac_table ON facility_data (facility_id, table_name);

-- ── managed_users ───────────────────────────────────────────────────────────
-- HQ-mastered directory pushed DOWN to assigned facilities. Holds an INITIAL
-- credential only; the facility owns the password after first change.
CREATE TABLE managed_users (
  id             text        PRIMARY KEY,
  username       text        NOT NULL UNIQUE,
  display_name   text        NOT NULL DEFAULT '',
  role           text        NOT NULL DEFAULT 'pa',
  permissions    text        NOT NULL DEFAULT '[]',
  hash           text,
  salt           text,
  must_change_pw smallint    NOT NULL DEFAULT 1 CHECK (must_change_pw IN (0,1)),
  status         text        NOT NULL DEFAULT 'active'
                 CHECK (status IN ('active','disabled')),
  created_at     timestamptz NOT NULL DEFAULT now()
);

-- SQLite declared no foreign keys here; both sides are added now because the
-- parent rows are HQ-owned and cascade is unambiguously correct — unassigning a
-- facility or removing a managed user should drop the assignment, and neither
-- side carries retention-bearing clinical data.
CREATE TABLE managed_user_facilities (
  user_id     text NOT NULL REFERENCES managed_users (id) ON DELETE CASCADE,
  facility_id text NOT NULL REFERENCES facilities    (id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, facility_id)
);

-- ── releases ────────────────────────────────────────────────────────────────
-- HQ imports a signed release once, then relays the bundle to enrolled
-- facilities so they never need internet access. Bundles live on disk in
-- data/releases/; this table is the index over them.
CREATE TABLE releases (
  channel    text        NOT NULL CHECK (channel IN ('facility','central')),
  version    text        NOT NULL,
  filename   text        NOT NULL,
  size       bigint      NOT NULL,
  sha256     text        NOT NULL,
  signature  text,
  sig_alg    text        NOT NULL DEFAULT 'ed25519',
  min_node   text,
  min_from   text,
  changelog  text        NOT NULL DEFAULT '[]',
  released   timestamptz,
  notes      text        NOT NULL DEFAULT '',
  status     text        NOT NULL DEFAULT 'published'
             CHECK (status IN ('published','yanked')),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (channel, version)
);

-- ── rollouts ────────────────────────────────────────────────────────────────
-- One active rollout per channel. The engine issues per-facility directives
-- from state + canary membership and auto-advances or pauses on reported health.
CREATE TABLE rollouts (
  channel    text        PRIMARY KEY CHECK (channel IN ('facility','central')),
  version    text        NOT NULL,
  state      text        NOT NULL DEFAULT 'paused'
             CHECK (state IN ('paused','canary','active','complete')),
  canary_ids text        NOT NULL DEFAULT '[]',
  notes      text        NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz
);

COMMIT;

-- ============================================================================
-- CHANGES FROM THE SQLITE SCHEMA — each is deliberate, flag any you disagree with
--
-- 1. CHECK constraints added on the four status/state/channel columns. SQLite
--    documented the allowed values only in a trailing comment; the application
--    enforced them. Now the database does too.
--
-- 2. facility_data.facility_id gains a foreign key to facilities. It had none.
--    A facility removed from the fleet should not leave orphaned synced rows,
--    and CASCADE matches what the existing "remove a facility" flow already
--    does by hand (it deletes the facility's data explicitly — see the v0.1.4
--    changelog entry).
--
-- 3. managed_user_facilities gains both foreign keys, CASCADE on each.
--
-- 4. sync_state.applied_through and facility_data.source_id are bigint, not
--    integer. They track facility-side row ids, which are 64-bit in principle;
--    an int4 ceiling here would be an avoidable future outage.
--
-- 5. releases.released and rollouts.created_at/updated_at were TEXT with no
--    default and are timestamptz here. created_at gains a default; the SQLite
--    version had none and relied on the caller.
-- ============================================================================
