// Facility colour themes.
//
// The colours themselves live in index.css as :root[data-theme="..."] blocks
// (generated by scripts/gen-themes.cjs). This module is the list the UI picks
// from and the one place that writes the attribute, so nothing else should
// touch document.documentElement.dataset.theme.
//
// Independent of light/dark, which is a class on the same element and a
// different storage key ('opspoint-theme').

export const DEFAULT_THEME = 'indigo'

// `swatch` is [primary-600, accent-500] — what a picker shows. Kept in step
// with the generated CSS by hand; there are five of them.
export const THEMES = [
  { key: 'indigo',  label: 'Indigo',  hint: 'Default',            swatch: ['#4f46e5', '#a855f7'] },
  { key: 'blue',    label: 'Blue',    hint: 'Cool and corporate', swatch: ['#2563eb', '#06b6d4'] },
  { key: 'teal',    label: 'Teal',    hint: 'OpsPoint heritage',  swatch: ['#0f766e', '#10b981'] },
  { key: 'emerald', label: 'Emerald', hint: 'Fresh and calm',     swatch: ['#047857', '#14b8a6'] },
  { key: 'rose',    label: 'Rose',    hint: 'Warm',               swatch: ['#db2777', '#d946ef'] },
]

export const THEME_KEYS = THEMES.map(t => t.key)
export const isValidTheme = (k) => THEME_KEYS.includes(k)
export const themeLabel = (k) => (THEMES.find(t => t.key === k) || THEMES[0]).label

const STORAGE_KEY = 'opspoint-facility-theme'

// Read the cached theme. Phase 3 makes the facility record authoritative and
// keeps this as the pre-paint cache, since facility settings only arrive after
// GET /api/data and the login page has no session at all.
export function readStoredTheme() {
  try {
    const v = localStorage.getItem(STORAGE_KEY)
    return isValidTheme(v) ? v : DEFAULT_THEME
  } catch {
    return DEFAULT_THEME   // private mode / storage blocked
  }
}

export function storeTheme(key) {
  try { localStorage.setItem(STORAGE_KEY, isValidTheme(key) ? key : DEFAULT_THEME) }
  catch { /* not fatal — the theme still applies for this page view */ }
}

// Indigo carries no attribute: it is the @theme default, so removing the
// attribute is what selects it.
export function applyTheme(key) {
  const el = document.documentElement
  const k = isValidTheme(key) ? key : DEFAULT_THEME
  if (k === DEFAULT_THEME) delete el.dataset.theme
  else el.dataset.theme = k
  return k
}

// Apply + persist in one step.
export function setTheme(key) {
  const k = applyTheme(key)
  storeTheme(k)
  return k
}
