#!/usr/bin/env bash
# =============================================================================
# OpsPoint for Linux: the installer, and afterwards the maintenance tool
# (installed as /usr/local/bin/opspoint).
#
#   sudo bash install.sh                              menus (arrow keys or number keys)
#   sudo bash install.sh --config answers.env --yes   unattended, no menus (automation, CI)
#   sudo opspoint                                     after installing: the same menus
#   opspoint doctor | export | import FILE | drill DIR | backups | settings | migrate | setup-code
#                                                     the command line, as the service account
#
# Options
#   --config FILE      answers, KEY=value lines (below); a question is asked for each
#                      one not given, unless --yes takes its default
#   --yes              no questions: the answers file and the defaults
#   --no-color         plain text (also NO_COLOR=1, and whenever the output isn't a terminal)
#   --version X.Y.Z    a release other than the newest
#   --bundle FILE --manifest FILE   install from files already here (no download)
#   --prefix DIR       where OpsPoint lives (default /opt/opspoint)
#   --dry-run          say what would happen; change nothing (no root needed)
#   --help
#
# Answers
#   TZ=America/Chicago            the facility's time zone (asked when this machine is on UTC)
#   PORT=3000                     OPSPOINT_DATA=/var/lib/opspoint
#   OPSPOINT_DB_DRIVER=sqlite     or pg, with DATABASE_URL=postgresql://user:pass@host:5432/db
#   PGSSLMODE=verify-full         TLS to Postgres: verify-full, verify-ca, require or disable
#                                 (default disable for a database on this machine)
#   SERVICE=systemd               or pm2 (when the machine has no systemd)
#   ADDRESS=ops.example.org       the name or address the setup link uses (default: this
#                                 machine's first network address)
# =============================================================================
set -uo pipefail

RELEASES="https://github.com/harrisb415/opspoint-releases/releases"
# The release signing key the in-app updater pins (updater.js): a bundle whose
# manifest it didn't sign is never installed.
PUBKEY="MCowBQYDK2VwAyEAT+OjqALSKqG9ZCLj8kON/A1VpxDd3tBDWkWlNn91jY4="
NODE_VERSION="24.20.0"          # installed under the prefix when the machine has no Node 20+
NODE_MIN_MAJOR=20
SERVICE_USER="opspoint"
ETC="/etc/opspoint"
CONFIG="$ETC/opspoint.config.json"
UNIT="/etc/systemd/system/opspoint.service"
BIN="/usr/local/bin/opspoint"
CLI_COMMANDS=" settings doctor migrate keys setup-code export import drill backups "

# ── brand (generated by scripts/gen-brand.cjs from packaging/brand.json) ──
BRAND_PRODUCT="OpsPoint"
BRAND_TITLE="OpsPoint Setup"
BRAND_TAGLINE="Residential operations"
BRAND_DOOR="◖▌░░◗"
HEX_NAVY="1E3A70"; A256_NAVY=24; A16_NAVY=34
HEX_GOLD="F5B82E"; A256_GOLD=214; A16_GOLD=33
HEX_WARM="FFE8A3"; A256_WARM=229; A16_WARM=97
HEX_SILVER="C5CBD3"; A256_SILVER=251; A16_SILVER=37
HEX_PASS="16A34A"; A256_PASS=34; A16_PASS=32
HEX_FAIL="DC2626"; A256_FAIL=160; A16_FAIL=31
MENU_QUESTION="What would you like to do?"
MENU_ITEMS=("1|install|Install OpsPoint" "2|upgrade|Upgrade or repair" "3|doctor|Health check" "4|backup|Back up or restore" "5|export|Export or import" "6|uninstall|Uninstall" "q|quit|Quit")
MENU_HINTS="↑↓ move · Enter select · Q quit"
W_CHECKING="Checking this machine"
W_INSTALLING="Installing"
W_DONE="OpsPoint is installed"
W_OPEN_SETUP="Open this link to finish setup"
W_SETUP_CODE="Setup code"
W_CODE_NOTE="works once, for 24 hours"
W_PHONE_NOTE="Scan it with a phone to finish setup there"
NEWT_THEME="root=,blue window=,blue border=lightgray,blue title=yellow,blue textbox=white,blue button=blue,yellow actbutton=yellow,blue compactbutton=lightgray,blue listbox=lightgray,blue actlistbox=blue,yellow sellistbox=yellow,blue actsellistbox=blue,yellow checkbox=lightgray,blue actcheckbox=blue,yellow entry=white,blue disentry=lightgray,blue label=lightgray,blue emptyscale=,blue fullscale=,yellow helpline=lightgray,blue roottext=yellow,blue"
# ── end brand ──

# ── Options ─────────────────────────────────────────────────────────────────
ANSWERS="" YES=0 DRY=0 NOCOLOR=0 WANT_VERSION="" BUNDLE="" MANIFEST="" PREFIX="/opt/opspoint" ACTION=""
CLI_ARGS=()
usage() { sed -n '3,/^# ====/p' "$0" | sed '$d; s/^# \{0,1\}//'; }
while [ $# -gt 0 ]; do
  case "$1" in
    --config) ANSWERS="${2:-}"; shift 2 ;;
    --yes|-y) YES=1; shift ;;
    --dry-run) DRY=1; shift ;;
    --no-color) NOCOLOR=1; shift ;;
    --version) WANT_VERSION="${2:-}"; shift 2 ;;
    --bundle) BUNDLE="${2:-}"; shift 2 ;;
    --manifest) MANIFEST="${2:-}"; shift 2 ;;
    --prefix) PREFIX="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    install|upgrade|repair|uninstall|menu) ACTION="$1"; shift ;;
    *)
      if [ -z "$ACTION" ] && [[ "$CLI_COMMANDS" == *" $1 "* ]]; then ACTION="cli"; CLI_ARGS=("$@"); break; fi
      echo "Unknown option: $1 (see --help)" >&2; exit 2 ;;
  esac
done
APP="$PREFIX/app"
NODE_HOME="$PREFIX/node"

# Character counts (${#var}, for lining text up) need a working UTF-8 locale:
# test what bash actually does — LANG can name a locale the machine lacks.
_glyph='░'
if [ "${#_glyph}" != 1 ]; then
  for l in C.UTF-8 C.utf8 en_US.UTF-8 en_US.utf8; do
    if locale -a 2>/dev/null | grep -qix "$l"; then export LC_ALL="$l"; break; fi
  done
fi
padr() { local s=$1 w=$2 n; n=$(( w - ${#s} )); [ "$n" -lt 0 ] && n=0; printf '%s%*s' "$s" "$n" ''; }

# ── Colour: 24-bit, then 256, then 16, else none ───────────────────────────
DEPTH=0
if [ "$NOCOLOR" = 0 ] && [ -z "${NO_COLOR:-}" ] && [ -t 1 ]; then
  case "${COLORTERM:-}" in
    truecolor|24bit) DEPTH=24 ;;
    *) n=$(tput colors 2>/dev/null || echo 0); if [ "${n:-0}" -ge 256 ]; then DEPTH=256; elif [ "${n:-0}" -ge 8 ]; then DEPTH=16; fi ;;
  esac
fi
fg() {  # fg NAME -> the escape for that palette colour, or nothing
  [ "$DEPTH" = 0 ] && return 0
  local hex a256 a16
  eval "hex=\$HEX_$1 a256=\$A256_$1 a16=\$A16_$1"
  case "$DEPTH" in
    24) printf '\033[38;2;%d;%d;%dm' "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}" ;;
    256) printf '\033[38;5;%dm' "$a256" ;;
    16) printf '\033[%dm' "$a16" ;;
  esac
}
bg() {  # bg NAME
  [ "$DEPTH" = 0 ] && return 0
  local hex a256 a16
  eval "hex=\$HEX_$1 a256=\$A256_$1 a16=\$A16_$1"
  case "$DEPTH" in
    24) printf '\033[48;2;%d;%d;%dm' "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}" ;;
    256) printf '\033[48;5;%dm' "$a256" ;;
    16) printf '\033[%dm' "$((a16 + 10))" ;;
  esac
}
OFF=""; BOLD=""; DIM=""
if [ "$DEPTH" != 0 ]; then OFF=$'\033[0m'; BOLD=$'\033[1m'; DIM=$'\033[2m'; fi
GOLD=$(fg GOLD); SILVER=$(fg SILVER); WARM=$(fg WARM); PASS=$(fg PASS); FAIL=$(fg FAIL); NAVYBG=$(bg NAVY)
TTY=0; { [ -t 0 ] && [ -t 1 ]; } && TTY=1
# (-x as well: `command -v` falls back to a whiptail that can't run)
WHIP=0; if [ "$TTY" = 1 ] && [ "$DEPTH" != 0 ] && [ -x "$(command -v whiptail 2>/dev/null)" ]; then WHIP=1; fi
export NEWT_COLORS="$NEWT_THEME"

# ── Saying things ───────────────────────────────────────────────────────────
say()  { printf '%s\n' "$*"; }
head1() { printf '\n   %s%s%s\n' "$GOLD$BOLD" "$*" "$OFF"; }
ok()   { printf '   %s✔%s %s\n' "$PASS" "$OFF" "$*"; }
bad()  { printf '   %s✖%s %s\n' "$FAIL" "$OFF" "$*"; }
note() { printf '   %s!%s %s\n' "$GOLD" "$OFF" "$*"; }
die()  { printf '\n   %s✖ %s%s\n\n' "$FAIL" "$*" "$OFF" >&2; exit 1; }

banner() {
  local ver="${1:-}" w=48 line l1 l2
  line=$(printf '─%.0s' $(seq 1 "$w"))
  l1="   $BRAND_DOOR   $BRAND_TITLE${ver:+ · v$ver}"
  l2="           $BRAND_TAGLINE"
  printf '\n  %s╭%s╮%s\n' "$NAVYBG$SILVER" "$line" "$OFF"
  printf '  %s│%s%s%s│%s\n' "$NAVYBG$SILVER" "$GOLD$BOLD" "$(padr "$l1" "$w")" "$OFF$NAVYBG$SILVER" "$OFF"
  printf '  %s│%s%s%s│%s\n' "$NAVYBG$SILVER" "$SILVER" "$(padr "$l2" "$w")" "$NAVYBG$SILVER" "$OFF"
  printf '  %s╰%s╯%s\n\n' "$NAVYBG$SILVER" "$line" "$OFF"
}

# A progress bar redrawn in place (one line per step when not a terminal).
BAR_W=20
progress() {  # progress PERCENT WORDS
  local pct=$1; shift
  local fill=$(( pct * BAR_W / 100 )) bar=""
  bar="$(printf '█%.0s' $(seq 1 $((fill > 0 ? fill : 1))))"; [ "$fill" = 0 ] && bar=""
  bar="$bar$(printf '░%.0s' $(seq 1 $((BAR_W - fill > 0 ? BAR_W - fill : 1))))"; [ "$fill" -ge "$BAR_W" ] && bar="$(printf '█%.0s' $(seq 1 "$BAR_W"))"
  if [ "$TTY" = 1 ]; then printf '\r\033[K   %s %s%s%s %3d%%  %s' "$W_INSTALLING" "$GOLD" "$bar" "$OFF" "$pct" "$*"
  else printf '   %s %3d%%  %s\n' "$W_INSTALLING" "$pct" "$*"; fi
}
progress_end() { [ "$TTY" = 1 ] && printf '\n'; return 0; }

# ── Asking things ───────────────────────────────────────────────────────────
# menu TITLE QUESTION "key|id|label"... -> prints the chosen id
# MENU_DEFAULT (an id) is where the highlight starts: Enter alone must never
# start something heavy (on an installed machine, the health check).
MENU_DEFAULT=""
menu() {
  local title=$1 question=$2; shift 2
  local items=("$@") i key id label start=0 n=$#
  for ((i = 0; i < n; i++)); do IFS='|' read -r key id label <<<"${items[$i]}"; [ "$id" = "$MENU_DEFAULT" ] && start=$i; done
  if [ "$WHIP" = 1 ]; then
    local args=() def
    for i in "${items[@]}"; do IFS='|' read -r key id label <<<"$i"; args+=("$key" "$label"); done
    IFS='|' read -r def id label <<<"${items[$start]}"
    local pick
    pick=$(whiptail --title " $title " --default-item "$def" --menu "\n$question" 18 64 "${#items[@]}" "${args[@]}" 3>&1 1>&2 2>&3) || { echo quit; return 0; }
    for i in "${items[@]}"; do IFS='|' read -r key id label <<<"$i"; [ "$key" = "$pick" ] && { echo "$id"; return 0; }; done
    echo quit; return 0
  fi
  if [ "$TTY" = 1 ] && [ "$DEPTH" != 0 ]; then
    # Arrow keys and number keys, redrawn in place.
    local sel=$start k rest
    printf '   %s\n\n' "$question" >&2
    while :; do
      for ((i = 0; i < n; i++)); do
        IFS='|' read -r key id label <<<"${items[$i]}"
        if [ "$i" = "$sel" ]; then printf '\033[K   %s▸ %s%s\n' "$GOLD$BOLD" "$label" "$OFF" >&2
        else printf '\033[K     %s%s%s\n' "$SILVER" "$label" "$OFF" >&2; fi
      done
      printf '\n\033[K   %s%s%s' "$DIM" "$MENU_HINTS" "$OFF" >&2
      IFS= read -rsn1 k </dev/tty || k=q
      if [ "$k" = $'\033' ]; then IFS= read -rsn2 -t 0.1 rest </dev/tty || rest=""; k="$k$rest"; fi
      case "$k" in
        $'\033[A') sel=$(( (sel + n - 1) % n )) ;;
        $'\033[B') sel=$(( (sel + 1) % n )) ;;
        '') IFS='|' read -r key id label <<<"${items[$sel]}"; printf '\n\n' >&2; echo "$id"; return 0 ;;
        *) for i in "${items[@]}"; do IFS='|' read -r key id label <<<"$i"
             if [ "$key" = "${k,,}" ]; then printf '\n\n' >&2; echo "$id"; return 0; fi; done ;;
      esac
      printf '\r\033[%dA' "$((n + 1))" >&2
    done
  fi
  # Plain numbered prompt.
  printf '   %s\n' "$question" >&2
  for i in "${items[@]}"; do IFS='|' read -r key id label <<<"$i"; printf '     %s) %s\n' "$key" "$label" >&2; done
  local answer
  while :; do
    printf '   Choose: ' >&2
    IFS= read -r answer || { echo quit; return 0; }
    for i in "${items[@]}"; do IFS='|' read -r key id label <<<"$i"; [ "$key" = "${answer,,}" ] && { echo "$id"; return 0; }; done
  done
}

# ask NAME QUESTION DEFAULT -> sets $NAME (answers file first; --yes takes the default)
ask() {
  local name=$1 question=$2 def=$3 val
  if [ -n "${!name:-}" ]; then return 0; fi
  if [ "$YES" = 1 ] || [ "$TTY" = 0 ]; then printf -v "$name" '%s' "$def"; return 0; fi
  if [ "$WHIP" = 1 ]; then
    val=$(whiptail --title " $BRAND_TITLE " --inputbox "\n$question" 11 70 "$def" 3>&1 1>&2 2>&3) || exit 1
  else
    printf '   %s %s[%s]%s ' "$question" "$DIM" "$def" "$OFF"
    IFS= read -r val || val=""
    [ -z "$val" ] && val="$def"
  fi
  printf -v "$name" '%s' "$val"
}
# yesno QUESTION DEFAULT(y|n) -> 0 for yes
yesno() {
  local q=$1 def=${2:-y} a
  if [ "$YES" = 1 ] || [ "$TTY" = 0 ]; then [ "$def" = y ]; return; fi
  if [ "$WHIP" = 1 ]; then
    if [ "$def" = y ]; then whiptail --title " $BRAND_TITLE " --yesno "\n$q" 10 70; else whiptail --title " $BRAND_TITLE " --defaultno --yesno "\n$q" 10 70; fi
    return
  fi
  printf '   %s %s ' "$q" "$([ "$def" = y ] && echo '[Y/n]' || echo '[y/N]')"
  IFS= read -r a || a=""
  a=${a:-$def}; [[ "${a,,}" == y* ]]
}

# ── Doing things (or, with --dry-run, saying so) ───────────────────────────
run() { if [ "$DRY" = 1 ]; then say "   would run: $*"; else "$@"; fi; }
runq() { if [ "$DRY" = 1 ]; then say "   would run: $*"; else "$@" >/dev/null 2>&1; fi; }   # its own output would break the progress line
write_file() {  # write_file PATH MODE OWNER CONTENT_SHOWN_IN_DRY_RUN < content
  local path=$1 mode=$2 owner=$3 shown=${4:-}
  if [ "$DRY" = 1 ]; then
    say "   would write $path ($mode, $owner)"; [ -n "$shown" ] && printf '%s\n' "$shown" | sed 's/^/     | /'
    cat >/dev/null; return 0
  fi
  local tmp; tmp=$(mktemp "${path}.XXXXXX") || return 1
  cat >"$tmp" && chmod "$mode" "$tmp" && chown "$owner" "$tmp" && mv -f "$tmp" "$path"
}

fetch() {  # fetch URL FILE
  if command -v curl >/dev/null 2>&1; then curl -fsSL --retry 3 -o "$2" "$1"
  elif command -v wget >/dev/null 2>&1; then wget -q -O "$2" "$1"
  else return 1; fi
}

installed() { [ -f "$APP/package.json" ] && [ -f "$CONFIG" ]; }
installed_version() { sed -n 's/^ *"version": *"\([^"]*\)".*/\1/p' "$APP/package.json" 2>/dev/null | head -1; }

# Node 20+ already here, or the one under the prefix; empty when neither.
NODE=""
find_node() {
  local cand v
  for cand in "$NODE_HOME/bin/node" "$(command -v node 2>/dev/null || true)"; do
    [ -n "$cand" ] && [ -x "$cand" ] || continue
    v=$("$cand" -p 'process.versions.node' 2>/dev/null) || continue
    if [ "${v%%.*}" -ge "$NODE_MIN_MAJOR" ] 2>/dev/null; then NODE="$cand"; NODE_FOUND="$v"; return 0; fi
  done
  return 1
}

install_node() {
  local arch tarball url sums dir
  case "$(uname -m)" in x86_64|amd64) arch=x64 ;; aarch64|arm64) arch=arm64 ;; *) die "No Node.js build for $(uname -m): install Node $NODE_MIN_MAJOR or later yourself, then run this again." ;; esac
  tarball="node-v$NODE_VERSION-linux-$arch.tar.xz"
  url="https://nodejs.org/dist/v$NODE_VERSION"
  if [ "$DRY" = 1 ]; then say "   would download $url/$tarball, check it against SHASUMS256.txt and unpack it into $NODE_HOME"; NODE="$NODE_HOME/bin/node"; return 0; fi
  dir=$(mktemp -d) || return 1
  fetch "$url/$tarball" "$dir/$tarball" && fetch "$url/SHASUMS256.txt" "$dir/SHASUMS256.txt" || { rm -rf "$dir"; die "Couldn't download Node.js from nodejs.org."; }
  ( cd "$dir" && grep " $tarball\$" SHASUMS256.txt | sha256sum -c --status ) || { rm -rf "$dir"; die "The Node.js download doesn't match nodejs.org's checksum: not installed."; }
  rm -rf "$NODE_HOME" && mkdir -p "$NODE_HOME" && tar -xJf "$dir/$tarball" -C "$NODE_HOME" --strip-components=1 --no-same-owner || { rm -rf "$dir"; die "Couldn't unpack Node.js."; }
  rm -rf "$dir"
  NODE="$NODE_HOME/bin/node"
}

# The release: its manifest (signed with the pinned key) and the bundle it names.
# Sets REL_VERSION and REL_BUNDLE (a verified file).
# The bundle into a folder of its own. --no-same-owner: a bundle built on Windows names owners
# that root in an unprivileged container can't assign (everything is chowned later anyway).
# umask 022 + --no-same-permissions: such a bundle also records every file and folder as
# writable by anyone (bsdtar has no modes to read there), and root would keep that.
unpack() {
  (umask 022 && mkdir -p "$1" && tar -xzf "$REL_BUNDLE" -C "$1" --no-same-owner --no-same-permissions)
}

get_release() {
  local dir mf bundle
  dir=$(mktemp -d) || return 1
  WORK="$dir"
  if [ -n "$BUNDLE" ]; then
    [ -n "$MANIFEST" ] || die "--bundle needs --manifest (the release's update-manifest.json), to check its signature."
    mf="$MANIFEST"; bundle="$BUNDLE"
  else
    local base="$RELEASES/latest/download"
    [ -n "$WANT_VERSION" ] && base="$RELEASES/download/v$WANT_VERSION"
    mf="$dir/update-manifest.json"
    if [ "$DRY" = 1 ]; then say "   would download $base/update-manifest.json and the bundle it names, and check its signature"; REL_VERSION="${WANT_VERSION:-latest}"; return 0; fi
    fetch "$base/update-manifest.json" "$mf" || die "Couldn't download the release manifest from $base."
  fi
  local out
  out=$("$NODE" -e '
    const c = require("crypto"), fs = require("fs");
    const m = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
    const pem = "-----BEGIN PUBLIC KEY-----\n" + process.argv[2] + "\n-----END PUBLIC KEY-----\n";
    const payload = Buffer.from(`${m.version}\n${m.size || 0}\n${String(m.sha256).toLowerCase()}`);
    const good = m.signature && c.verify(null, payload, c.createPublicKey(pem), Buffer.from(String(m.signature), "base64"));
    if (!good || !/^[0-9a-f]{64}$/i.test(String(m.sha256)) || !/^\d+\.\d+\.\d+$/.test(String(m.version))) { console.log("BAD"); process.exit(0); }
    console.log([m.version, String(m.sha256).toLowerCase(), m.size || 0, m.url || ""].join(" "));
  ' "$mf" "$PUBKEY" 2>/dev/null) || out="BAD"
  [ "$out" = "BAD" ] && die "The release manifest isn't signed with OpsPoint's release key: nothing was installed."
  local ver sha size url
  read -r ver sha size url <<<"$out"
  if [ -z "$BUNDLE" ]; then
    bundle="$dir/opspoint-$ver.tar.gz"
    case "$url" in "$RELEASES"/*) ;; *) die "The manifest names a download outside OpsPoint's releases: $url" ;; esac
    fetch "$url" "$bundle" || die "Couldn't download $url."
  fi
  local got; got=$(sha256sum "$bundle" | cut -d' ' -f1)
  [ "$got" = "$sha" ] || die "The bundle doesn't match its signed manifest (sha256): nothing was installed."
  [ "$(stat -c %s "$bundle")" = "$size" ] || die "The bundle's size doesn't match its signed manifest: nothing was installed."
  REL_VERSION="$ver"; REL_BUNDLE="$bundle"
}

# Run the OpsPoint command line as the service account, with its settings.
cli() {
  local cmd=("$NODE" "$APP/server/cli/opspoint.js" "$@")
  if [ "$(id -u)" = 0 ]; then (cd "$APP" && runuser -u "$SERVICE_USER" -- env OPSPOINT_CONFIG="$CONFIG" "${cmd[@]}")
  elif [ "$(id -un)" = "$SERVICE_USER" ]; then (cd "$APP" && OPSPOINT_CONFIG="$CONFIG" "${cmd[@]}")
  else die "Run this with sudo (the command line runs as the $SERVICE_USER account)."; fi
}

machine_zone() {
  local z=""
  z=$(timedatectl show -p Timezone --value 2>/dev/null || true)
  [ -z "$z" ] && [ -f /etc/timezone ] && z=$(cat /etc/timezone)
  [ -z "$z" ] && [ -L /etc/localtime ] && z=$(readlink /etc/localtime | sed 's|.*/zoneinfo/||')
  printf '%s' "${z:-UTC}"
}
first_address() { hostname -I 2>/dev/null | awk '{print $1}'; }
port_free() { ! (ss -ltnH 2>/dev/null | awk '{print $4}' | grep -Eq "[:.]$1\$"); }

# PM2 (machines without systemd): installed beside Node when missing, run as the
# service account with its state in the data folder.
PM2=""
ensure_pm2() {
  [ "$SERVICE" = pm2 ] || return 0
  PM2=$(command -v pm2 2>/dev/null || true)
  [ -z "$PM2" ] && [ -x "$(dirname "$NODE")/pm2" ] && PM2="$(dirname "$NODE")/pm2"
  if [ -z "$PM2" ]; then
    run env PATH="$(dirname "$NODE"):$PATH" "$(dirname "$NODE")/npm" install -g pm2 --no-audit --no-fund >/dev/null 2>&1 || [ "$DRY" = 1 ] || die "Couldn't install PM2."
    PM2="$(dirname "$NODE")/pm2"
  fi
}
pm2u() { run runuser -u "$SERVICE_USER" -- env PATH="$(dirname "$NODE"):$PATH" HOME="$OPSPOINT_DATA" PM2_HOME="$OPSPOINT_DATA/.pm2" OPSPOINT_CONFIG="$CONFIG" "$PM2" "$@"; }
service_start() {
  if [ "$SERVICE" = pm2 ]; then
    ensure_pm2
    if [ "$DRY" = 0 ] && pm2u describe opspoint >/dev/null 2>&1; then pm2u restart opspoint >/dev/null; else pm2u start "$APP/bootstrap.js" --name opspoint >/dev/null; fi
    pm2u save >/dev/null 2>&1
  else runq systemctl enable --now opspoint; fi
}
service_stop()    { if [ "$SERVICE" = pm2 ]; then ensure_pm2; pm2u stop opspoint >/dev/null 2>&1; else run systemctl stop opspoint; fi; }
service_restart() { if [ "$SERVICE" = pm2 ]; then service_start; else run systemctl restart opspoint; fi; }

# The maintenance tool comes from the release (inside the signed bundle) when it can.
install_tool() {
  local src=""
  if [ -f "$APP/packaging/linux/install.sh" ]; then src="$APP/packaging/linux/install.sh"
  elif [ -f "$0" ] && head -1 "$0" 2>/dev/null | grep -q bash; then src="$0"; fi
  if [ "$DRY" = 1 ]; then say "   would install the maintenance tool as $BIN"; return 0; fi
  if [ -n "$src" ] && [ "$src" != "$PREFIX/install.sh" ]; then cp -f "$src" "$PREFIX/install.sh"; fi
  [ -f "$PREFIX/install.sh" ] || { note "The maintenance tool isn't in this release: run this installer again for it."; return 0; }
  chmod 0755 "$PREFIX/install.sh" && ln -sf "$PREFIX/install.sh" "$BIN"
}

# The encrypted SQLite driver loads from the binaries it ships (no compiler
# needed; npm runs with --ignore-scripts). Postgres installs never load it.
sqlite_loads() {
  [ "${OPSPOINT_DB_DRIVER:-sqlite}" = sqlite ] || return 0
  (cd "$APP" && "$NODE" -e "new (require('better-sqlite3-multiple-ciphers'))(':memory:').prepare('select 1').get()" >/dev/null 2>&1)
}

probe_url() {  # probe_url URL -> 0 when it answers 2xx
  if command -v curl >/dev/null 2>&1; then curl -fsSk --max-time 2 "$1" >/dev/null 2>&1
  else wget -q -T 2 --no-check-certificate -O /dev/null "$1" 2>/dev/null; fi
}
wait_healthy() {  # up to 90 s for /healthz
  [ "$DRY" = 1 ] && { say "   would wait for http://127.0.0.1:$PORT/healthz"; return 0; }
  local i scheme=http; [ -f "$OPSPOINT_DATA/cert.pem" ] && scheme=https
  for i in $(seq 1 45); do
    probe_url "$scheme://127.0.0.1:$PORT/healthz" && return 0
    sleep 2
  done
  return 1
}

# ── Settings questions (install) ────────────────────────────────────────────
load_answers() {
  [ -n "$ANSWERS" ] || return 0
  [ -r "$ANSWERS" ] || die "Can't read the answers file $ANSWERS."
  local line k v
  # Read as data, never run: KEY=value lines; quotes around the value are dropped.
  while IFS= read -r line || [ -n "$line" ]; do
    line="${line%$'\r'}"
    [[ "$line" =~ ^[[:space:]]*(#|$) ]] && continue
    [[ "$line" =~ ^[[:space:]]*([A-Z_][A-Z0-9_]*)=(.*)$ ]] || die "Not a KEY=value line in $ANSWERS: $line"
    k="${BASH_REMATCH[1]}"; v="${BASH_REMATCH[2]}"
    v="${v#\"}"; v="${v%\"}"; v="${v#\'}"; v="${v%\'}"
    case "$k" in TZ|PORT|OPSPOINT_DATA|OPSPOINT_DB_DRIVER|DATABASE_URL|PGSSLMODE|SERVICE|ADDRESS) printf -v "$k" '%s' "$v" ;;
      *) die "$ANSWERS: $k isn't an answer this installer takes (see --help)." ;; esac
  done <"$ANSWERS"
}

questions() {
  local zone; zone=$(machine_zone)
  if [ -z "${TZ:-}" ]; then
    if [ "$zone" = "UTC" ] || [ "$zone" = "Etc/UTC" ]; then
      ask TZ "This machine's clock is on UTC. The facility's time zone (for example America/Chicago):" "America/Chicago"
    else
      TZ="$zone"
    fi
  fi
  ask PORT "Port OpsPoint answers on:" "3000"
  ask OPSPOINT_DATA "Folder for the database, photos and backups:" "/var/lib/opspoint"
  if [ -z "${OPSPOINT_DB_DRIVER:-}" ]; then
    if [ "$YES" = 1 ] || [ "$TTY" = 0 ]; then OPSPOINT_DB_DRIVER=sqlite
    else
      case "$(menu "$BRAND_TITLE" "Where does the database live?" "1|sqlite|SQLite on this machine (encrypted; simplest)" "2|pg|Postgres on another server")" in
        pg) OPSPOINT_DB_DRIVER=pg ;; quit) exit 0 ;; *) OPSPOINT_DB_DRIVER=sqlite ;; esac
    fi
  fi
  if [ "$OPSPOINT_DB_DRIVER" = pg ]; then
    ask DATABASE_URL "Postgres connection string (postgresql://user:password@host:5432/database):" ""
    [[ "${DATABASE_URL:-}" =~ ^postgres(ql)?:// ]] || die "DATABASE_URL must be a postgresql:// connection string."
    # TLS to the database: verified by default; a database on this machine needs none.
    local dbhost ssl_default=verify-full
    dbhost=$(printf '%s' "$DATABASE_URL" | sed -E 's|^[a-z]+://([^@]*@)?(\[[^]]*\]\|[^/:?]*).*|\2|')
    case "$dbhost" in localhost|127.0.0.1|'[::1]') ssl_default=disable ;; esac
    ask PGSSLMODE "TLS to the database (verify-full, verify-ca, require or disable):" "$ssl_default"
    case "$PGSSLMODE" in disable|require|verify-ca|verify-full) ;; *) die "PGSSLMODE must be verify-full, verify-ca, require or disable." ;; esac
  fi
  if [ -z "${SERVICE:-}" ]; then
    if command -v systemctl >/dev/null 2>&1 && [ -d /run/systemd/system ]; then SERVICE=systemd; else SERVICE=pm2; fi
  fi
  [[ "$PORT" =~ ^[0-9]+$ ]] && [ "$PORT" -ge 1 ] && [ "$PORT" -le 65535 ] || die "PORT must be a number from 1 to 65535."
  [[ "$OPSPOINT_DATA" = /* ]] || die "OPSPOINT_DATA must be a full path (starting with /)."
  case "$OPSPOINT_DB_DRIVER" in sqlite|pg) ;; *) die "OPSPOINT_DB_DRIVER must be sqlite or pg." ;; esac
  case "$SERVICE" in systemd|pm2) ;; *) die "SERVICE must be systemd or pm2." ;; esac
  if [ "$SERVICE" = pm2 ] && [ "$PORT" -lt 1024 ]; then die "Under pm2 OpsPoint can't take port $PORT (below 1024): use 1024 or above, behind a proxy for 80/443."; fi
}

settings_json() {  # the settings file: written by Node, so every value is quoted correctly
  "${NODE:-node}" -e '
    const e = process.env, s = { OPSPOINT_PROFILE: "linux-local", TZ: e.A_TZ, PORT: Number(e.A_PORT), OPSPOINT_DATA: e.A_DATA, OPSPOINT_DB_DRIVER: e.A_DRIVER };
    if (e.A_DRIVER === "pg") { s.DATABASE_URL = e.A_URL; s.PGSSLMODE = e.A_SSL; }
    process.stdout.write(JSON.stringify(s, null, 2) + "\n");
  ' 2>/dev/null || printf '{\n  "OPSPOINT_PROFILE": "linux-local",\n  "TZ": "%s",\n  "PORT": %s,\n  "OPSPOINT_DATA": "%s",\n  "OPSPOINT_DB_DRIVER": "%s"\n}\n' "$A_TZ" "$A_PORT" "$A_DATA" "$A_DRIVER"
}

unit_text() {
  cat <<EOF
[Unit]
Description=$BRAND_PRODUCT ($BRAND_TAGLINE)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$SERVICE_USER
Group=$SERVICE_USER
WorkingDirectory=$APP
Environment=OPSPOINT_CONFIG=$CONFIG
Environment=NODE_ENV=production
ExecStart="$NODE" $APP/bootstrap.js
Restart=on-failure
RestartSec=5
# 78 = a setting is wrong: starting again won't help, the log says what to fix.
RestartPreventExitStatus=78
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full
$([ "$PORT" -lt 1024 ] && echo "AmbientCapabilities=CAP_NET_BIND_SERVICE")

[Install]
WantedBy=multi-user.target
EOF
}

# ── Install ─────────────────────────────────────────────────────────────────
do_install() {
  local t0=$SECONDS
  head1 "$W_CHECKING"
  if [ "$DRY" = 0 ]; then
    [ "$(id -u)" = 0 ] || die "Run the installer with sudo: it creates a service account and a system service."
    [ "$(uname -s)" = Linux ] || die "This installer is for Linux. On Windows, use the OpsPoint Setup program."
  fi
  if installed && [ "$DRY" = 0 ]; then
    note "OpsPoint $(installed_version) is already installed in $PREFIX."
    yesno "Upgrade or repair it instead?" n && { do_upgrade; return; }
    exit 0
  fi
  load_answers
  local os; os=$( (. /etc/os-release 2>/dev/null && echo "${PRETTY_NAME:-$ID}") || uname -sr)
  ok "$os, $(uname -m)"
  if find_node; then ok "Node $NODE_FOUND found ($NODE)"; else note "No Node.js $NODE_MIN_MAJOR or later: Node $NODE_VERSION will be installed in $NODE_HOME"; fi
  command -v curl >/dev/null 2>&1 || command -v wget >/dev/null 2>&1 || [ -n "$BUNDLE" ] || die "Neither curl nor wget is installed: install one, then run this again."
  command -v tar >/dev/null 2>&1 || die "tar is not installed."
  questions
  if port_free "$PORT"; then ok "Port $PORT is free"; else bad "Port $PORT is in use"; [ "$DRY" = 1 ] || die "Something else answers on port $PORT: choose another (PORT=...)."; fi
  local parent="$OPSPOINT_DATA"; while [ ! -d "$parent" ] && [ "$parent" != / ]; do parent=$(dirname "$parent"); done
  local free_gb; free_gb=$(df -Pk "$parent" 2>/dev/null | awk 'NR==2 {printf "%d", $4/1048576}')
  if [ "${free_gb:-0}" -ge 2 ]; then ok "${free_gb} GB free disk space"; else bad "Only ${free_gb:-0} GB free on $parent"; [ "$DRY" = 1 ] || die "OpsPoint needs at least 2 GB free for its data and backups."; fi
  ok "Time zone $TZ"
  ok "Database: $([ "$OPSPOINT_DB_DRIVER" = pg ] && echo "Postgres at $(printf '%s' "$DATABASE_URL" | sed -E 's|^[a-z]+://([^@]*@)?([^/?]*).*|\2|')" || echo "SQLite in $OPSPOINT_DATA")"
  ok "Runs as the $SERVICE_USER account, under $SERVICE"
  echo

  progress 5 "Getting Node.js…"
  if [ -z "$NODE" ]; then progress_end; install_node; fi
  progress 20 "Downloading OpsPoint…"
  get_release; [ "$DRY" = 1 ] && progress_end
  progress 40 "Unpacking$([ "$REL_VERSION" = latest ] || echo " v$REL_VERSION")…"
  if [ "$DRY" = 1 ]; then say "   would unpack the bundle into $APP"
  else
    id "$SERVICE_USER" >/dev/null 2>&1 || useradd --system --home-dir "$OPSPOINT_DATA" --shell /usr/sbin/nologin "$SERVICE_USER" || die "Couldn't create the $SERVICE_USER account."
    mkdir -p "$OPSPOINT_DATA" "$ETC" && unpack "$APP" || die "Couldn't unpack the bundle."
  fi
  progress 55 "Installing packages…"
  if [ "$DRY" = 1 ]; then say "   would run: npm ci --omit=dev --ignore-scripts (in $APP)"
  else
    local npm="$(dirname "$NODE")/npm"; [ -x "$npm" ] || npm=$(command -v npm)
    (cd "$APP" && PATH="$(dirname "$NODE"):$PATH" "$npm" ci --omit=dev --ignore-scripts --no-audit --no-fund >"$WORK/npm.log" 2>&1) || { progress_end; tail -20 "$WORK/npm.log" >&2; die "npm ci failed (above)."; }
    sqlite_loads || { progress_end; die "The SQLite driver has no build for this machine ($(uname -m)): use Postgres (OPSPOINT_DB_DRIVER=pg), or see docs/SUPPORT.md."; }
  fi
  progress 75 "Writing the settings…"
  A_TZ="$TZ" A_PORT="$PORT" A_DATA="$OPSPOINT_DATA" A_DRIVER="$OPSPOINT_DB_DRIVER" A_URL="${DATABASE_URL:-}" A_SSL="${PGSSLMODE:-verify-full}" export A_TZ A_PORT A_DATA A_DRIVER A_URL A_SSL
  local shown; shown=$(settings_json | sed -E 's|("DATABASE_URL": "[a-z]+://[^:/@]*:)[^@]*@|\1•••@|')
  settings_json | write_file "$CONFIG" 0640 "root:$SERVICE_USER" "$shown" || die "Couldn't write $CONFIG."
  run chown -R "$SERVICE_USER:$SERVICE_USER" "$APP" "$OPSPOINT_DATA"
  run chmod 0750 "$OPSPOINT_DATA"
  progress 85 "Registering the service…"
  if [ "$SERVICE" = systemd ]; then
    unit_text | write_file "$UNIT" 0644 root:root "$(unit_text)" || die "Couldn't write $UNIT."
    run systemctl daemon-reload
  fi
  install_tool
  progress 90 "Starting OpsPoint…"
  service_start
  wait_healthy || { progress_end; die "OpsPoint didn't start. See: journalctl -u opspoint -n 50"; }
  progress 100 "Started."
  progress_end
  finish_card "$t0"
}

finish_card() {
  local t0=${1:-$SECONDS} addr scheme=http code="" link
  echo; head1 "Health check"
  if [ "$DRY" = 1 ]; then say "   would run: opspoint doctor"
  else cli doctor | sed -n '3,$p' | sed '/^$/d; s/^/ /'; fi
  addr="${ADDRESS:-$(first_address)}"; addr="${addr:-$(hostname)}"
  [ -f "$OPSPOINT_DATA/cert.pem" ] && scheme=https
  link="$scheme://$addr:$PORT/setup"
  if { [ "$scheme" = http ] && [ "$PORT" = 80 ]; } || { [ "$scheme" = https ] && [ "$PORT" = 443 ]; }; then link="$scheme://$addr/setup"; fi
  if [ "$DRY" = 0 ]; then code=$(cli setup-code 2>/dev/null | sed -n 's/^Setup code: \([A-Z0-9-]*\).*/\1/p'); fi
  echo
  printf '   %s%s%s  (%ds)\n\n' "$GOLD$BOLD" "$W_DONE" "$OFF" "$((SECONDS - t0))"
  printf '   %s:\n   %s%s%s\n' "$W_OPEN_SETUP" "$WARM$BOLD" "$link" "$OFF"
  if [ -n "$code" ]; then printf '   %s: %s%s%s (%s)\n' "$W_SETUP_CODE" "$WARM$BOLD" "$code" "$OFF" "$W_CODE_NOTE"
  elif [ "$DRY" = 0 ]; then printf '   %s\n' "Setup is already finished here: sign in as usual."; fi
  if command -v qrencode >/dev/null 2>&1 && [ "$TTY" = 1 ] && [ "$DRY" = 0 ]; then echo; qrencode -t ANSIUTF8 -m 2 "$link" | sed 's/^/   /'; printf '   %s\n' "$W_PHONE_NOTE"; fi
  printf '\n   %sLater: sudo opspoint  (upgrade, health check, backup, export)%s\n\n' "$DIM" "$OFF"
}

# ── Upgrade or repair ───────────────────────────────────────────────────────
read_config() {  # SERVICE / PORT / OPSPOINT_DATA from what is installed
  [ -f "$CONFIG" ] || return 0
  PORT=$(sed -n 's/^ *"PORT": *\([0-9]*\).*/\1/p' "$CONFIG" | head -1); PORT=${PORT:-3000}
  OPSPOINT_DATA=$(sed -n 's/^ *"OPSPOINT_DATA": *"\([^"]*\)".*/\1/p' "$CONFIG" | head -1); OPSPOINT_DATA=${OPSPOINT_DATA:-/var/lib/opspoint}
  OPSPOINT_DB_DRIVER=$(sed -n 's/^ *"OPSPOINT_DB_DRIVER": *"\([^"]*\)".*/\1/p' "$CONFIG" | head -1); OPSPOINT_DB_DRIVER=${OPSPOINT_DB_DRIVER:-sqlite}
  if [ -f "$UNIT" ]; then SERVICE=systemd; else SERVICE=pm2; fi
}

do_upgrade() {
  installed || die "OpsPoint isn't installed in $PREFIX."
  [ "$DRY" = 1 ] || [ "$(id -u)" = 0 ] || die "Run this with sudo."
  read_config; find_node || die "Node.js $NODE_MIN_MAJOR or later is missing: run the installer again."
  local from; from=$(installed_version)
  head1 "Upgrade or repair (installed: v$from)"
  get_release
  if [ "$REL_VERSION" = "$from" ]; then yesno "v$from is the newest. Repair it (put its files back as released)?" y || return 0
  else yesno "Upgrade v$from to v$REL_VERSION?" y || return 0; fi
  progress 10 "Stopping OpsPoint…"; service_stop
  progress 25 "Keeping v$from beside it…"
  run rm -rf "$PREFIX/app.previous"; run mv "$APP" "$PREFIX/app.previous"
  progress 40 "Unpacking v$REL_VERSION…"
  # Into an empty folder: nothing of v$from stays behind among the new version's files.
  if [ "$DRY" = 0 ]; then unpack "$APP" || { progress_end; rollback "$from" "v$REL_VERSION didn't unpack"; }; fi
  progress 60 "Installing packages…"
  if [ "$DRY" = 0 ]; then
    local npm="$(dirname "$NODE")/npm"; [ -x "$npm" ] || npm=$(command -v npm)
    (cd "$APP" && PATH="$(dirname "$NODE"):$PATH" "$npm" ci --omit=dev --ignore-scripts --no-audit --no-fund >"$WORK/npm.log" 2>&1) || { progress_end; tail -20 "$WORK/npm.log" >&2; rollback "$from" "v$REL_VERSION's packages didn't install"; }
    sqlite_loads || { progress_end; rollback "$from"; }
    chown -R "$SERVICE_USER:$SERVICE_USER" "$APP"
  fi
  install_tool
  progress 85 "Starting v$REL_VERSION…"; service_restart
  if wait_healthy; then progress 100 "Running v$REL_VERSION."; progress_end; ok "Upgraded to v$REL_VERSION"
  else progress_end; rollback "$from"; fi
}

rollback() {
  local why=${2:-"v$REL_VERSION didn't start"}
  bad "$why: putting v$1 back"
  service_stop
  run rm -rf "$APP"; run mv "$PREFIX/app.previous" "$APP"
  service_restart
  wait_healthy && die "$why; v$1 is running again. See: journalctl -u opspoint -n 80" \
    || die "Neither version started. See: journalctl -u opspoint -n 80"
}

# ── Uninstall ───────────────────────────────────────────────────────────────
do_uninstall() {
  installed || die "OpsPoint isn't installed in $PREFIX."
  [ "$DRY" = 1 ] || [ "$(id -u)" = 0 ] || die "Run this with sudo."
  read_config
  head1 "Uninstall"
  # Asked, defaulting to no; `uninstall --yes` names the action, so it goes ahead (the data still stays).
  if [ "$YES" = 0 ]; then yesno "Remove OpsPoint from this machine? The data in $OPSPOINT_DATA stays unless you choose otherwise next." n || return 0; fi
  service_stop
  if [ "$SERVICE" = systemd ]; then run systemctl disable opspoint >/dev/null 2>&1; run rm -f "$UNIT"; run systemctl daemon-reload
  else pm2u delete opspoint >/dev/null 2>&1; pm2u save >/dev/null 2>&1; fi
  run rm -rf "$APP" "$PREFIX/app.previous" "$NODE_HOME" "$PREFIX/install.sh"; run rm -f "$BIN"
  [ "$DRY" = 1 ] || rmdir "$PREFIX" 2>/dev/null || true
  if yesno "Also delete the settings file ($CONFIG)? It holds this install's settings and any database password." y; then run rm -rf "$ETC"; fi
  local typed=""
  if [ "$YES" = 0 ] && [ "$TTY" = 1 ]; then
    printf '   %sTo delete every record, photo and backup in %s too, type DELETE (anything else keeps them):%s ' "$FAIL" "$OPSPOINT_DATA" "$OFF"
    IFS= read -r typed || typed=""
  fi
  if [ "$typed" = "DELETE" ]; then run rm -rf "$OPSPOINT_DATA"; run userdel "$SERVICE_USER"; ok "Removed OpsPoint and its data."
  else ok "Removed OpsPoint. The data is still in $OPSPOINT_DATA."; fi
}

# ── Backup, export, import ──────────────────────────────────────────────────
do_backup() {
  installed || die "OpsPoint isn't installed in $PREFIX."
  read_config; find_node || die "Node.js is missing: run the installer again."
  case "$(menu "Back up or restore" "Back up or restore" "1|export|Export now (one encrypted file with everything)" "2|drill|Restore drill: the newest export into a scratch install" "3|list|Show the database backups" "b|back|Back")" in
    export) cli export --out "$OPSPOINT_DATA/exports" ;;
    drill) cli drill "$OPSPOINT_DATA/exports" ;;
    # The command line knows where they go: a folder chosen in setup (backup_dir) or beside the database.
    list) cli backups ;;
  esac
}
do_export() {
  installed || die "OpsPoint isn't installed in $PREFIX."
  read_config; find_node || die "Node.js is missing: run the installer again."
  case "$(menu "Export or import" "Export or import" "1|export|Export to a file" "2|import|Import an export (into this new, empty install)" "b|back|Back")" in
    export) local out; out="$OPSPOINT_DATA/exports"; ask EXPORT_TO "Folder or file for the export:" "$out"; cli export --out "$EXPORT_TO" ;;
    import)
      ask IMPORT_FILE "The export file to import:" ""
      [ -f "$IMPORT_FILE" ] || die "There is no file at $IMPORT_FILE."
      run install -o "$SERVICE_USER" -m 0600 "$IMPORT_FILE" "$OPSPOINT_DATA/import.opspoint"
      service_stop
      cli import "$OPSPOINT_DATA/import.opspoint"; local rc=$?
      run rm -f "$OPSPOINT_DATA/import.opspoint"
      service_start
      [ "$rc" = 0 ] && finish_card ;;
  esac
}

# ── The menu ────────────────────────────────────────────────────────────────
main_menu() {
  while :; do
    banner "$(installed && installed_version)"
    if installed; then MENU_DEFAULT=doctor; else MENU_DEFAULT=install; fi
    local pick; pick=$(menu "$BRAND_TITLE" "$MENU_QUESTION" "${MENU_ITEMS[@]}")
    MENU_DEFAULT=""
    case "$pick" in
      install) do_install ;;
      upgrade) do_upgrade ;;
      doctor) installed || die "OpsPoint isn't installed in $PREFIX."; read_config; find_node; cli doctor ;;
      backup) do_backup ;;
      export) do_export ;;
      uninstall) do_uninstall; exit 0 ;;
      quit|"") exit 0 ;;
    esac
    [ "$TTY" = 1 ] || exit 0
    printf '\n   %sPress Enter for the menu%s' "$DIM" "$OFF"; IFS= read -r _ || exit 0
  done
}

WORK=""
trap '[ -n "$WORK" ] && rm -rf "$WORK"' EXIT

case "${ACTION:-}" in
  cli) installed || die "OpsPoint isn't installed in $PREFIX."; find_node || die "Node.js is missing: run the installer again."; cli "${CLI_ARGS[@]}"; exit $? ;;
  install) banner; do_install ;;
  upgrade|repair) banner "$(installed_version)"; do_upgrade ;;
  uninstall) do_uninstall ;;
  menu) main_menu ;;
  *)
    if [ "$YES" = 1 ] || [ "$TTY" = 0 ]; then banner; if installed && [ "$DRY" = 0 ]; then do_upgrade; else do_install; fi
    else main_menu; fi ;;
esac
