#!/usr/bin/env node
'use strict';
/**
 * The installers' look, from packaging/brand.json (deployment plan: "Installer
 * look and feel") into the files that must stand alone: the Linux installer is
 * downloaded as one file, the Windows maintenance tool runs as one script.
 *
 *   node scripts/gen-brand.cjs           rewrite the generated block in each
 *   node scripts/gen-brand.cjs --check   exit 1 if any block is out of date
 *
 * tests/packaging.test.js runs --check.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const brand = JSON.parse(fs.readFileSync(path.join(ROOT, 'packaging', 'brand.json'), 'utf8'));

// 16-colour names -> SGR foreground codes; newt (whiptail) knows only these names.
const SGR16 = { black: 30, red: 31, green: 32, yellow: 33, blue: 34, magenta: 35, cyan: 36, white: 37, brightwhite: 97 };
const NEWT = { navy: 'blue', gold: 'yellow', silver: 'lightgray', warm: 'white' };
const P = brand.palette;
for (const [name, c] of Object.entries(P)) {
  if (!/^#[0-9A-F]{6}$/.test(c.hex) || !Number.isInteger(c.ansi256) || !(c.ansi16 in SGR16)) throw new Error(`brand.json: palette.${name} is not hex + ansi256 + a 16-colour name`);
}

function newtTheme() {
  const bgN = NEWT.navy, g = NEWT.gold, s = NEWT.silver, w = NEWT.warm;
  return [
    `root=,${bgN}`, `window=,${bgN}`, `border=${s},${bgN}`, `title=${g},${bgN}`, `textbox=${w},${bgN}`,
    `button=${bgN},${g}`, `actbutton=${g},${bgN}`, `compactbutton=${s},${bgN}`,
    `listbox=${s},${bgN}`, `actlistbox=${bgN},${g}`, `sellistbox=${g},${bgN}`, `actsellistbox=${bgN},${g}`,
    `checkbox=${s},${bgN}`, `actcheckbox=${bgN},${g}`, `entry=${w},${bgN}`, `disentry=${s},${bgN}`, `label=${s},${bgN}`,
    `emptyscale=,${bgN}`, `fullscale=,${g}`, `helpline=${s},${bgN}`, `roottext=${g},${bgN}`,
  ].join(' ');
}

const q = (s) => `"${String(s).replace(/(["\\$`])/g, '\\$1')}"`;            // bash double quotes
const pq = (s) => `'${String(s).replace(/'/g, "''")}'`;                      // PowerShell single quotes

function bashBlock() {
  const lines = [
    `BRAND_PRODUCT=${q(brand.product)}`,
    `BRAND_TITLE=${q(brand.setupTitle)}`,
    `BRAND_TAGLINE=${q(brand.tagline)}`,
    `BRAND_DOOR=${q(brand.door)}`,
  ];
  for (const name of ['navy', 'gold', 'warm', 'silver', 'pass', 'fail']) {
    const c = P[name], N = name.toUpperCase();
    lines.push(`HEX_${N}=${q(c.hex.slice(1))}; A256_${N}=${c.ansi256}; A16_${N}=${SGR16[c.ansi16]}`);
  }
  lines.push(`MENU_QUESTION=${q(brand.menu.question)}`);
  lines.push(`MENU_ITEMS=(${brand.menu.items.map((i) => q(`${i.key}|${i.id}|${i.label}`)).join(' ')})`);
  lines.push(`MENU_HINTS=${q(brand.menu.hints)}`);
  const W = { checking: 'W_CHECKING', installing: 'W_INSTALLING', done: 'W_DONE', openSetup: 'W_OPEN_SETUP', setupCode: 'W_SETUP_CODE', codeNote: 'W_CODE_NOTE', phoneNote: 'W_PHONE_NOTE' };
  for (const [k, v] of Object.entries(W)) lines.push(`${v}=${q(brand.words[k])}`);
  lines.push(`NEWT_THEME=${q(newtTheme())}`);
  return lines.join('\n');
}

function psBlock() {
  const lines = [
    `$BrandProduct = ${pq(brand.product)}`,
    `$BrandTitle   = ${pq(brand.setupTitle)}`,
    `$BrandTagline = ${pq(brand.tagline)}`,
    `$BrandDoor    = ${pq(brand.door)}`,
    `$BrandDoorConsole = ${pq(brand.doorConsole)}`,
    '$Palette = @{',
  ];
  for (const name of ['navy', 'gold', 'warm', 'silver', 'pass', 'fail']) {
    const c = P[name];
    lines.push(`  ${name.padEnd(6)} = @{ Hex = ${pq(c.hex)}; A256 = ${c.ansi256}; A16 = ${SGR16[c.ansi16]} }`);
  }
  lines.push('}');
  lines.push(`$MenuQuestion = ${pq(brand.menu.question)}`);
  lines.push('$MenuItems = @(');
  for (const i of brand.menu.items) lines.push(`  @{ Key = ${pq(i.key)}; Id = ${pq(i.id)}; Label = ${pq(i.label)} }`);
  lines.push(')');
  lines.push(`$MenuHints = ${pq(brand.menu.hints)}`);
  lines.push('$Words = @{');
  for (const [k, v] of Object.entries(brand.words)) lines.push(`  ${k} = ${pq(v)}`);
  lines.push('}');
  return lines.join('\n');
}

const TARGETS = [
  { file: path.join('packaging', 'linux', 'install.sh'), start: '# ── brand (generated by scripts/gen-brand.cjs from packaging/brand.json) ──', end: '# ── end brand ──', body: bashBlock },
  { file: path.join('packaging', 'windows', 'opspoint.ps1'), start: '# ── brand (generated by scripts/gen-brand.cjs from packaging/brand.json) ──', end: '# ── end brand ──', body: psBlock },
];

function apply(check) {
  const stale = [];
  for (const t of TARGETS) {
    const file = path.join(ROOT, t.file);
    if (!fs.existsSync(file)) continue;
    const text = fs.readFileSync(file, 'utf8');
    const eol = text.includes('\r\n') ? '\r\n' : '\n';
    const a = text.indexOf(t.start), b = text.indexOf(t.end);
    if (a < 0 || b < a) throw new Error(`${t.file}: no generated brand block`);
    const next = text.slice(0, a) + t.start + eol + t.body().split('\n').join(eol) + eol + text.slice(b);
    if (next !== text) {
      stale.push(t.file);
      if (!check) fs.writeFileSync(file, next);
    }
  }
  return stale;
}

if (require.main === module) {
  const check = process.argv.includes('--check');
  const stale = apply(check);
  if (check && stale.length) {
    process.stdout.write(`Out of date (run node scripts/gen-brand.cjs): ${stale.join(', ')}\n`);
    process.exit(1);
  }
  process.stdout.write(stale.length ? `${check ? 'Stale' : 'Rewrote'}: ${stale.join(', ')}\n` : 'Brand blocks are up to date.\n');
}

module.exports = { apply, bashBlock, psBlock, newtTheme };
